FinalProject.UI/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA;
using Microsoft.AspNet.Identity;
using FinalProject.UI.Models;

namespace FinalProject.UI.Controllers
{
    public class CoursesController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Courses
        public ActionResult Index()
        {
            return View(db.Courses);
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }

            List<Lesson> courseLessons = db.Lessons.Where(c => c.CourseID == id && c.IsActive && c.Course.IsActive).ToList();

            ViewBag.CourseName = course.CourseName;
            ViewBag.CourseDescription = course.Description;
            ViewBag.ValidFor = course.ValidFor;

            return View(courseLessons);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CourseID,CourseName,Description,IsActive,ValidFor")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CourseID,CourseName,Description,IsActive,ValidFor")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject.UI/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA;
using Microsoft.AspNet.Identity;
using FinalProject.UI.Models;
using System.Web.Security;
using IdentitySample.Models;
using System.Dynamic;
using Microsoft.AspNet.Identity.Owin;

namespace FinalProject.UI.Controllers
{    
    public class EmployeesController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Employees
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Index()
        {
            if (User.IsInRole("Manager"))
            {
                List<ManagerVM> emps = new List<ManagerVM>();
                string mgrID = User.Identity.GetUserId();
                foreach (var employee in db.Employees.Where(e => e.ManagerID == mgrID))
                {
                    int expSoon = 0;

                    ManagerVM mvm = new ManagerVM();
                    mvm.UserID = employee.UserID;
                    mvm.EmployeeName = employee.FirstName + " " + employee.LastName;
                    foreach (var cc in db.CourseCompletions.Where(u => u.UserID == employee.UserID).Include(c => c.Course))
                    {
                        if (cc.DateCompleted.AddYears(cc.Course.ValidFor) <= DateTime.Now.AddMonths(1))
                        {
                            expSoon++;
                        }
                    }
                    mvm.ExpCourses = expSoon;
                    int incCount = 0;
                    foreach (var course in db.Courses.Where(c=>c.IsActive))
                    {
                        if (db.CourseCompletions.Where(u => u.UserID == employee.UserID && u.CourseID == course.CourseID).Count() == 0)
                        {
                            incCount++;
                        }
                    }
                    mvm.IncCourses = incCount;
                    emps.Add(mvm);
                    TempData["employees"] = emps;
                }
                return RedirectToAction("ManagerEmployeeView");
            }
            var employees = db.Employees.Include(e => e.Employee1);
            return View(employees.ToList());
        }

        [Authorize(Roles = "Manager")]
        public ActionResult ManagerEmployeeView()
        {
            var employees = TempData["employees"];
            return View(employees);
        }

        [Authorize(Roles = "Employee")]
        public ActionResult EmployeeProgress()
        {
            var id = User.Identity.GetUserId();
            List<EmployeeVM> completeCourses = new List<EmployeeVM>();

            foreach (var course in db.CourseCompletions.Where(cc => cc.UserID == id && cc.Course.IsActive).Include(c => c.Course))
            {
                EmployeeVM evm = new EmployeeVM();
                evm.UserID = id;
                evm.CourseName = course.Course.CourseName;
                evm.Description = course.Course.Description;
                evm.ValidFor = course.Course.ValidFor;
                evm.LessonCount = db.Lessons.Where(x => x.CourseID == course.CourseID && x.IsActive).Count();
                evm.DateCompleted = course.DateCompleted;
                completeCourses.Add(evm);
            }

            List<IncompleteCourseVM> incompleteCourses = new List<IncompleteCourseVM>();

            foreach (var course in db.Courses.Where(c => c.IsActive))
            {
                if (db.CourseCompletions.Where(c => c.UserID == id && c.CourseID == course.CourseID).Count() == 0)
                {
                    IncompleteCourseVM icvm = new IncompleteCourseVM();
                    icvm.CourseID = course.CourseID;
                    icvm.CourseName = course.CourseName;
                    icvm.TotalLessons = db.Lessons.Where(c => c.CourseID == course.CourseID && c.IsActive).Count();
                    icvm.LessonsComplete = db.LessonViews.Where(u => u.UserID == id && u.Lesson.CourseID == course.CourseID).Count();
                    incompleteCourses.Add(icvm);
                }
            }

            dynamic empCourses = new ExpandoObject();
            empCourses.Incomplete = incompleteCourses;
            empCourses.Complete = completeCourses;

            return View(empCourses);
        }

        // GET: Employees/Details/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            List<EmployeeVM> completeCourses = new List<EmployeeVM>();

            foreach (var course in db.CourseCompletions.Where(cc => cc.UserID == id).Include(c => c.Course))
            {
                EmployeeVM evm = new EmployeeVM();
                evm.UserID = id;
                evm.CourseName = course.Course.CourseName;
                evm.Description = course.Course.Description;
                evm.ValidFor = course.Course.ValidFor;
                evm.LessonCount = db.Lessons.Where(x => x.CourseID == course.CourseID).Count();
                evm.DateCompleted = course.DateCompleted;
                completeCourses.Add(evm);
            }

            List<IncompleteCourseVM> incompleteCourses = new List<IncompleteCourseVM>();

            foreach (var course in db.Courses.Where(c => c.IsActive))
            {
                if (db.CourseCompletions.Where(c => c.UserID == id && c.CourseID == course.CourseID).Count() == 0)
                {
                    IncompleteCourseVM icvm = new IncompleteCourseVM();
                    icvm.CourseID = course.CourseID;
                    icvm.CourseName = course.CourseName;
                    icvm.TotalLessons = db.Lessons.Where(c => c.CourseID == course.CourseID && c.IsActive && c.Course.IsActive).Count();
                    icvm.LessonsComplete = db.LessonViews.Where(u => u.UserID == id && u.Lesson.CourseID == course.CourseID).Count();
                    incompleteCourses.Add(icvm);
                }
            }
            dynamic empCourses = new ExpandoObject();
            empCourses.Complete = completeCourses;
            empCourses.Incomplete = incompleteCourses;
            ViewBag.Name = employee.FirstName + " " + employee.LastName;
            var UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = UserManager.FindById(employee.UserID);
            ViewBag.Email = user.Email;

            return View(empCourses);
        }

        // GET: Employees/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManagerID = new SelectList(db.Employees, "UserID", "FirstName", employee.ManagerID);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "UserID,FirstName,LastName,ManagerID")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ManagerID = new SelectList(db.Employees, "UserID", "FirstName", employee.ManagerID);
            return View(employee);
        }

        // GET: Employees/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(string id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Agency - @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />
    <!--
    //////////////////////////////////////////////////////

    FREE HTML5 TEMPLATE
    DESIGNED & DEVELOPED by FreeHTML5.co

    Website: 		http://freehtml5.co/
    Email: 			info@freehtml5.co
    Twitter: 		http://twitter.com/fh5co
    Facebook: 		https://www.facebook.com/fh5co

    //////////////////////////////////////////////////////
     -->
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/content/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/content/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/content/css/bootstrap.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="~/content/css/style.css">
    <!-- Modernizr JS -->
    <script src="~/content/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/css/custom.css" rel="stylesheet" />
</head>
<body>

    <div class="fh5co-loader"></div>

    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="container">
                <div class="row">
                    <div class="col-xs-5 text-right menu-1">
                        <ul>
                            @if (User.IsInRole("Manager"))
                            {
                                <li><a href="@Url.Action("Index", "Employees")">My Staff</a></li>
                            }
                            else if (User.IsInRole("Admin"))
                            {
                                <li><a href="@Url.Action("Index", "Employees")">All Employees</a></li>
                            }
                            else if (User.IsInRole("Employee"))
                            {
                                <li><a href="@Url.Action("EmployeeProgress", "Employees")">My Progress</a></li>
                            }
                            <li><a href="@Url.Action("Index", "Courses")">All Courses</a></li>
                            <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-2 text-center">
                        <div id="fh5co-logo"><a href="@Url.Action("Index", "Home")">Agency.</a></div>
                    </div>
                    <div class="col-xs-5 text-left menu-1">
                        <ul>
                            
                            @Html.Partial("_LoginPartial")
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url(../../content/images/img_bg_1.jpg);">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center">
                        <div class="display-t">
                            <div class="display-tc animate-box" data-animate-effect="fadeIn">
                                <h1>@ViewBag.Title</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div id="fh5co-about">
            <div class="container">
                <div class="about-content">
                    <div class="row animate-box">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>

        <footer id="fh5co-footer" role="contentinfo">
            <div class="container">               
                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block"><a href="@Url.Content("~/Content/JonathanBakerDocumentation.pdf")" target="_blank">Project Documentation</a></small>
                            <small class="block">&copy; 2019 Jonathan Baker. All Rights Reserved.</small>
                            <small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a></small>
                        </p>                        
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!-- jQuery -->
    <script src="~/content/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/content/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/content/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/content/js/jquery.waypoints.min.js"></script>
    <!-- Main -->
    <script src="~/content/js/main.js"></script>
    <script src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(function () {
            $('.menu-1 li').each(function () {
                var fullAnchor = $(this).find('a').attr('href');
                var aController = fullAnchor.split('/');
                var fullPath = (window.location.pathname + location.search).substr(1);
                var pController = fullPath.split('/');
                if (aController[1] == pController[0]) {
                    $(this).addClass('active');
                }
                if (((aController[1] == 'Home') || (aController[1] == 'Account')) && window.location.pathname != fullAnchor) {
                    $(this).removeClass('active');
                }
            });
        });
    </script>
    @RenderSection("scripts", false)
</body>
</html>

FinalProject.UI/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>