FinalProject.UI/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA;
using Microsoft.AspNet.Identity;
using FinalProject.UI.Models;

namespace FinalProject.UI.Controllers
{
    public class CoursesController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Courses
        public ActionResult Index()
        {
            return View(db.Courses);
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }

            List<Lesson> courseLessons = db.Lessons.Where(c => c.CourseID == id && c.IsActive && c.Course.IsActive).ToList();

            ViewBag.CourseName = course.CourseName;
            ViewBag.CourseDescription = course.Description;
            ViewBag.ValidFor = course.ValidFor;

            return View(courseLessons);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "CourseID,CourseName,Description,IsActive,ValidFor")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "CourseID,CourseName,Description,IsActive,ValidFor")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject.UI/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using System.Net.Mail;
using Microsoft.AspNet.Identity.Owin;
using IdentitySample.Models;

namespace FinalProject.UI.Controllers
{
    public class LessonsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Lessons
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var lessons = db.Lessons.Include(l => l.Course);
            return View(lessons.ToList());
        }

        // GET: Lessons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }

            string userid = User.Identity.GetUserId();
            if (User.IsInRole("Employee"))
            {
                if (db.LessonViews.Where(lv => lv.UserID == userid && lv.LessonID == id).Count() == 0)
                {
                    LessonView newLessonView = new LessonView();
                    newLessonView.DateViewed = DateTime.Now;
                    newLessonView.UserID = User.Identity.GetUserId();
                    newLessonView.LessonID = (int)id;

                    db.LessonViews.Add(newLessonView);
                }
                else
                {
                    LessonView updateLessonView = db.LessonViews.Where(lv => lv.UserID == userid && lv.LessonID == id).Single();
                    updateLessonView.DateViewed = DateTime.Now;

                    db.Entry(updateLessonView).State = EntityState.Modified;
                }
                db.SaveChanges();
                if (db.Lessons.Where(l => l.CourseID == lesson.CourseID).Count() == db.LessonViews.Include(lv => lv.Lesson).Where(lv => lv.UserID == userid && lv.Lesson.CourseID == lesson.CourseID).Count())
                {
                    if (db.CourseCompletions.Where(cc => cc.UserID == userid && cc.CourseID == lesson.CourseID).Count() == 0)
                    {
                        CourseCompletion newCourseCompletion = new CourseCompletion();
                        newCourseCompletion.UserID = User.Identity.GetUserId();
                        newCourseCompletion.CourseID = lesson.CourseID;
                        newCourseCompletion.DateCompleted = DateTime.Now;

                        db.CourseCompletions.Add(newCourseCompletion);
                    }
                    else
                    {
                        CourseCompletion updateCourseCompletion = db.CourseCompletions.Where(cc => cc.UserID == userid && cc.CourseID == lesson.CourseID).Single();
                        Course course = db.Courses.Find(lesson.CourseID);
                        DateTime exp = updateCourseCompletion.DateCompleted.AddYears(course.ValidFor).AddMonths(-1);
                        if (db.LessonViews.Where(lv=>lv.DateViewed >= exp && 
                            lv.UserID == userid && lv.Lesson.CourseID == lesson.CourseID).Count() == db.Lessons.Where(l => l.CourseID == lesson.CourseID).Count())
                        {
                            updateCourseCompletion.DateCompleted = DateTime.Now;
                            db.Entry(updateCourseCompletion).State = EntityState.Modified;
                        }                     
                    }

                    Employee e = db.Employees.Find(userid);

                    var UserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    var user = UserManager.FindById(e.ManagerID);

                    string body = $"{e.FirstName} {e.LastName} has completed the course {lesson.Course.CourseName} as of {DateTime.Now:MM/dd/yyyy}.";

                    MailMessage msg = new MailMessage("no-reply@jdbaker.net",
                                                      user.Email,
                                                      "Email from Agency - " + e.FirstName + " " + e.LastName + " completed a course.",
                                                      body);

                    SmtpClient client = new SmtpClient("mail.jdbaker.net");
                    client.Credentials = new NetworkCredential("no-reply@jdbaker.net", "EMAIL PASSWORD HERE");

                    using (client)
                    {
                        client.Send(msg);
                    }
                    db.SaveChanges();
                }
            }

            return View(lesson);
        }

        // GET: Lessons/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName");
            return View();
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "LessonID,LessonTitle,CourseID,Introduction,VideoURL,PdfFileName,IsActive")] Lesson lesson, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
                //Allowing File Uploads
                string pdfName = "Not Available";

                if (pdfFile != null)
                {
                    pdfName = pdfFile.FileName;
                    string ext = pdfName.Substring(pdfName.LastIndexOf('.')).ToLower();
                    if (ext == ".pdf")
                    {
                        pdfFile.SaveAs(Server.MapPath("~/Content/Files/" + pdfName));
                    }
                }
                lesson.PdfFileName = pdfName;

                //Stripping relevant information from YouTube URL
                if (lesson.VideoURL != null)
                {
                    var v = lesson.VideoURL.IndexOf("v=");
                    var amp = lesson.VideoURL.IndexOf("&", v);
                    string vid;
                    if (amp == -1)
                    {
                        vid = lesson.VideoURL.Substring(v + 2);
                    }
                    else
                    {
                        vid = lesson.VideoURL.Substring(v + 2, amp - (v + 2));
                    }
                    lesson.VideoURL = vid;
                }

                db.Lessons.Add(lesson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        // GET: Lessons/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        // POST: Lessons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "LessonID,LessonTitle,CourseID,Introduction,VideoURL,PdfFileName,IsActive")] Lesson lesson, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
                //Allowing File Uploads
                string pdfName = "Not Available";

                if (pdfFile != null)
                {
                    pdfName = pdfFile.FileName;
                    string ext = pdfName.Substring(pdfName.LastIndexOf('.')).ToLower();
                    if (ext == ".pdf")
                    {
                        pdfFile.SaveAs(Server.MapPath("~/Content/Files/" + pdfName));
                    }
                }
                lesson.PdfFileName = pdfName;

                //Stripping relevant information from YouTube URL
                if (lesson.VideoURL != null && lesson.VideoURL.Contains("v="))
                {
                    var v = lesson.VideoURL.IndexOf("v=");
                    var amp = lesson.VideoURL.IndexOf("&", v);
                    string vid;
                    if (amp == -1)
                    {
                        vid = lesson.VideoURL.Substring(v + 2);
                    }
                    else
                    {
                        vid = lesson.VideoURL.Substring(v + 2, amp - (v + 2));
                    }
                    lesson.VideoURL = vid;
                }

                db.Entry(lesson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        // GET: Lessons/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);

FinalProject.UI/Views/Lessons/Create.cshtml
@model FinalProject.DATA.Lesson

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lesson</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LessonTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LessonTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LessonTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Introduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PdfFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pdfFile" />
                @*@Html.EditorFor(model => model.PdfFileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PdfFileName, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinalProject.UI/Views/Lessons/Delete.cshtml
@model FinalProject.DATA.Lesson

@{
    ViewBag.Title = "Delete " + Model.LessonTitle;
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lesson</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LessonTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LessonTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Introduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Introduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PdfFileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PdfFileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.CourseName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinalProject.UI/Views/Lessons/Details.cshtml
@model FinalProject.DATA.Lesson
@{
    ViewBag.Title = Model.LessonTitle;
}

<dl class="dl-horizontal">

    <dt>
        @Html.DisplayNameFor(model => model.Introduction)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Introduction)
    </dd>
</dl>
<div class="lesson">
    <div class="lessonitem">
        @if (Model.PdfFileName != "Not Available")
        {
                    <a href="@Url.Content("~/Content/Files/" + Model.PdfFileName)" target="_blank">Click to View Supplementary Document</a>
        }
    </div>
    <div class="lessonitem">
        @if (Model.VideoURL != null)
        {
            <iframe width="560" height="315" src="https://www.youtube.com/embed/@Model.VideoURL" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        }
    </div>
    <div class="lessonitem">
        <p>
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.LessonID }) @:|
    }

            @Html.ActionLink("Back to Course", "Details", "Courses", new { id = Model.CourseID }, null)
        </p>
    </div>
</div>

FinalProject.UI/Views/Lessons/Edit.cshtml
@model FinalProject.DATA.Lesson

@{
    ViewBag.Title = "Edit " + Model.LessonTitle;
}
@using (Html.BeginForm("Edit", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lesson</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LessonID)

        <div class="form-group">
            @Html.LabelFor(model => model.LessonTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LessonTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LessonTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Introduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PdfFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pdfFile" />
                @*@Html.EditorFor(model => model.PdfFileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PdfFileName, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinalProject.UI/Views/Lessons/Index.cshtml
@model IEnumerable<FinalProject.DATA.Lesson>

@{
    ViewBag.Title = "All Lessons";
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LessonTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Introduction)
            </th>
            <th>
                Video?
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PdfFileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="names">
                    @Html.DisplayFor(modelItem => item.LessonTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Introduction)
                </td>
                <td>
                    @if (item.VideoURL != null)
                    {
                        @:Yes
            }
                </td>
                <td>
                    <a href="@Url.Content("~/Content/Files/" + @item.PdfFileName)" target="_blank">Click to View Document</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.CourseName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.LessonID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.LessonID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.LessonID })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
    $(document).ready( function () {
        $('.table').DataTable({
            paging: false,
            searching: false,
            info: false,
            "initComplete": function (settings, json) {
                $(".table").wrap("<div style='overflow:auto; width:100%;position:relative;'></div>");
            },
        });
    } );
    </script>
}